Feat/salva id sentimentos
grupotesseract/jornadasolar pull request #112
Opened 2021-07-23 14:58 UTC by ThaisMap

- novos registros de sentimentos no diário serão salvos com id
- registros antigos que forem atualizados também vão ser salvos com id
- adiciona uma flag no diário para sentimentos salvos com id, para ajudar na migração

Finish #178935830

2021-07-28 22:40 UTC, kellynvd requested changes
Deixei algums comentários e tem mais 2 pontos:

1- deveria estar funcionando normalmente mesmo sem a migração? Porque acessi com meu user e está dando erro:

![Screenshot from 2021-07-28 19 30 51](https://user-images.githubusercontent.com/13313889/127404749-54bb2599-18fd-4504-9a44-68a04583ddd2.png)

Na develop não da erro, então acredito que esteja relacionado com essas alterações mesmo.
user: _kellynvd@gmail.com_
senha: _123321_

2- Ficou alguns console.log() no código, Não comentei em todos então tem que dar uma revisada :)

2021-07-28 22:40 UTC, kellynvd commented on src/components/diario/SentimentosCheckboxGroup.tsx
> +    const getSentimentosUsuario = async () => {
Acho que isso isso pode estar em uma função, tipo a dos hábitos (`getGrupoDeHabitosIniciais`) pra não deixar essa lógica no componente. O que acha?

2021-07-28 22:40 UTC, kellynvd commented on src/services/sentimentos/GetSentimentosByUserId.ts
> +    return Sentimentos.map(sentimento => new Sentimento(sentimento))
Acho que aqui o ideal seria o repository já retornar os **Sentimentos** instanciado e não o service fazer isso

2021-08-04 11:36 UTC, kellynvd approved these changes

2021-08-11 12:55 UTC, evandrododo approved these changes

2021-08-11 12:55 UTC, merged