v1.0.0
grupotesseract/jornadasolar pull request #126
Opened 2021-09-22 18:21 UTC by evandrododo

Utilizando a nomenclatura de versão para 1.0.0 seguindo o [versionamento semântico](https://semver.org/).
Considerando como completas as funcionalidades de hábitos, sentimentos, anotações, meditações, gráficos, notificações, internacionalização e perfil; além de ajustes de interface, funções do firebase e tela de adminitração do sistema

2021-09-22 19:52 UTC, ThaisMap approved these changes

2021-09-23 12:32 UTC, ThaisMap requested changes

2021-09-23 12:32 UTC, ThaisMap commented on src/repositories/RegistrosRepository.ts
> +            grupoRegistro.habitos?.foreach(habito => {
Aqui era pra ser 
`grupoRegistro.habitos?.forEach(habito => {`

2021-09-23 18:09 UTC, evandrododo commented on src/repositories/RegistrosRepository.ts
> +            grupoRegistro.habitos?.foreach(habito => {
```suggestion
            grupoRegistro.habitos?.forEach(habito => {
```

2021-10-06 13:11 UTC, ThaisMap approved these changes

2021-10-06 13:12 UTC, kellynvd approved these changes

2021-10-06 13:12 UTC, merged