Feat: usa collection novidades
grupotesseract/jornadasolar pull request #89
Opened 2021-06-16 15:25 UTC by ThaisMap

- Adiciona service para consultar se tem alguma novidade para exibir a partir da data atual, página informada e novidades dispensadas pelo usuário
- Ajusta componente novidade para exibir dados da collection ao invés de dados fixos
- Ajusta páginas do app para exibir o componente Novidade

2021-06-16 17:09 UTC, ThaisMap commented
Ref #178378564

2021-06-21 19:05 UTC, kellynvd commented on src/services/novidades/GetNovidadeValida.ts
> +interface IGetNovidadesValida {
Como é śo uma novidade acho que aqui pode ser Novidade no singular, e o  retorno também: `return novidadeValida`

2021-06-21 19:06 UTC, kellynvd requested changes
Fiz alguns testes e anotei alguns pontos:

- [x] Criei uma novidade pra `/configuracoes` mas não apareceu
- [ ] Criei duas novidades marcando a opção "Aparece só uma vez", mas elas continuam aparecendo mesmo saindo e voltando da página
- [ ] Criei uma novidade com data final de hoje mas ela não aparece
    - Talvez por causa do horário
- [ ] Acho que a verificação da data final pode ficar direto no repositório junto com a data inicial
- [ ] Acho que é bom limitarmos os caracteres do Título no cadastro da Novidade porque adicionei um com titulo grande e quebrou o layout por causa da div com o texto "Novo"

2021-06-21 20:04 UTC, evandrododo approved these changes
tentei passar o HOC `withUser` pra dentro do componente Novidade, pra evitar ficar pegando o user em toda página, mas isso quebrou a tipagem do componente e precisaria de um _refactor_ nos tipos 😔 então deixei como tava mesmo.
Acho que vale pensarmos nisso em futuras _sprints_ pra evitar a dependência de propriedades.
Além do que a Kellyn notou no review dela não tenho nada a acrescentar, ajustando isso por mim tá aprovado,

2021-06-23 12:13 UTC, ThaisMap commented on src/services/novidades/GetNovidadeValida.ts
> +interface IGetNovidadesValida {
Ok

2021-06-25 12:32 UTC, kellynvd requested changes
Só ficou pendente ainda o ajustes do título, fiz alguns teste mas ainda "quebra" o layout

![Screenshot from 2021-06-25 09 12 12](https://user-images.githubusercontent.com/13313889/123424713-987c6800-d597-11eb-8c20-86e5e70fc1db.png)

Aqui o "Novo" ficou desalinhado
![Screenshot from 2021-06-25 09 15 50](https://user-images.githubusercontent.com/13313889/123424729-9c0fef00-d597-11eb-9c0c-bcc82459efd0.png)

2021-06-29 11:01 UTC, kellynvd requested changes
Ficou certinho agora e gostei do helperText :blush: , porém quando clico em "Nova novidade" ele começa com `undefined / 25`

![Screenshot from 2021-06-29 07 55 03](https://user-images.githubusercontent.com/13313889/123786327-f1a60d80-d8af-11eb-8392-a652795fbe1d.png)

2021-06-29 14:07 UTC, kellynvd approved these changes

2021-06-29 14:07 UTC, merged