Preenche hábitos dos usuários
grupotesseract/jornadasolar pull request #98
Opened 2021-07-09 01:07 UTC by evandrododo

- Function criada preencher os gruposDeHabitos e os habitos de todos os usuários que não tiverem a collection grupoDeHabitos
- Também subi uma pasta `saved_data` que pode ser importada usando o comando incluído no package.json: `npm run serve:saved`, os dados atualmente simulam um bd antes de executar a função *preencheGruposDeHabitos*

Finishes #178642582

2021-07-12 11:49 UTC, ThaisMap approved these changes

2021-07-13 12:30 UTC, kellynvd commented
@evandrododo anotei algumas coisas fazendo os testes:

- O hábito personalizado da collection `habitos` precisa ser adicionado com o **mesmo id** na collection habitos do grupo Personalizados pois no diario estamos salvando esse id quando o user marca o hábito
- O nome da collection do usuário, no banco de desenvolvimento e produção, está `user` e não users, aí precisa alterar nas funções
- Eu vi que só preenche os grupos de hábitos no user se estiver vazio, nesse caso precisasmo cuidar pra **não rodar** a função `migrarHabitosPersonalizados` antes da `preencheGruposDeHabitosUsers` porque a primeira cria um grupo personalizado e então a segunda não vai criar os demais grupos - ou ajustar pra criar só os que não existem
- Ao rodar `preencheGruposDeHabitosUsers`, dentro da collection de hábitos tá salvando um campo `id` e `idDoHabitoModelo` com o mesmo valor, mas acho que esse `id` não é necessário

2021-07-13 12:34 UTC, kellynvd requested changes
@evandrododo anotei algumas coisas fazendo os testes:

- [x] O hábito personalizado da collection `habitos` precisa ser adicionado com o **mesmo id** na collection habitos do grupo Personalizados pois no diario estamos salvando esse id quando o user marca o hábito
- [x]  O nome da collection do usuário, no banco de desenvolvimento e produção, está `user` e não users, aí precisa alterar nas funções
- [x] Eu vi que só preenche os grupos de hábitos no user se estiver vazio, nesse caso precisasmo cuidar pra **não rodar** a função `migrarHabitosPersonalizados` antes da `preencheGruposDeHabitosUsers` porque a primeira cria um grupo personalizado e então a segunda não vai criar os demais grupos - ou ajustar pra criar só os que não existem
- [x]  Ao rodar `preencheGruposDeHabitosUsers`, dentro da collection de hábitos tá salvando um campo `id` e `idDoHabitoModelo` com o mesmo valor, mas acho que esse `id` não é necessário

2021-07-16 11:28 UTC, kellynvd approved these changes

2021-07-16 19:55 UTC, merged