feat: copia sentimentos modelos ao criar usuário
grupotesseract/jornadasolar pull request #99
Opened 2021-07-13 11:37 UTC by ThaisMap

- adiciona entity, repository e service para sentimentos modelos

2021-07-13 11:38 UTC, ThaisMap commented
Finishes #178797817

2021-07-15 18:54 UTC, evandrododo approved these changes

2021-07-16 12:52 UTC, kellynvd commented on src/repositories/UsersRepository.ts
> +  private async createUserSentimentos(userId: string): Promise<void> {
Pra esse método eu criaria um repositório de Sentimentos com um método create ou add que cria um sentimento na subcollection de sentimentos do usuário. Aí chamaria aqui no UsersRepository o service ao inves de chamar o método privado. Não está errado desta foma, mas acho que fica mais separado organizado se tiver em um repository e services separados pra essa subcollection. Assim também podemos já usar esse repositório e service quando usuário quiser adicionar novos sentimentos. O que acha?

2021-07-16 12:53 UTC, kellynvd requested changes
tudo certinho, só deixei uma sugestão em relação ao método de criar sentimentos

2021-07-19 12:21 UTC, ThaisMap commented on src/repositories/UsersRepository.ts
> +  private async createUserSentimentos(userId: string): Promise<void> {
Faz sentido mesmo.

2021-07-19 18:14 UTC, kellynvd approved these changes
show :clap:

2021-07-19 18:28 UTC, merged